# 1.Specify the compose file format; we're using the last one. 
#   If you're curious, at https://docs.docker.com/compose/compose-file/compose-versioning/ 
#   you can find an extensive description on the difference among versions
version: '3' 
# 2.Specify the list of services that will be built. In our case, app (Ruby on Rails) and web (NGINX)
services:  
  
  web:    
    image: 850620121738.dkr.ecr.us-east-2.amazonaws.com/docker-test-ecs
    build:      
      context: .
      dockerfile: ./docker/web/Dockerfile    
    # 2.3.Like depends_on, links expresses dependency among services. In our case, app and web
    
    # 2.4.Binds port 80 for public connections
    ports:      
      - 80:80